# ---------------------------------------------
# Owner: Baldhor
# Code status: completed
# Compile status: UNCOMPILED !
# Test status: UNTESTED !
# ---------------------------------------------

# ---------------------------------------------
# ESPHome configuration for Sonoff 4CH pro r2 device in purpose to handle wired heaters.
# 
# Important:
#   - Wired heater are heating when no signal, and not heating when there are a signal
#   - At boot, we don't want to heat by default
#     => Telays must be ON by default at startup!
#   - We want to avoid over heating in case the connection to the "thermostat" is lost
#     => The relays should turn ON after a timeout if no news!
#     => The thermostat must publish a new command before the timeout expire
#   - We want to avoid turning ON/OFF the relays repeatedly (it could damage them)
#     => A minimum delay must be respected before the new state is applied
# 
# Key points:
#   - Use native api
#   - Switch entities exposed are 'inversed' and do not control the relays directly, but
#       through an individual minimum delay
#     => ON means 'heat', meaning the relays 'should be' OFF
#     => OFF means 'don't heat', meaning the relays 'should be' ON
#     /!\ 'Should be' state will be applied only after the apply delay
#   - Binary sensors exposed (linked to the buttons) toggle the linked switch entity
#   - Switch entities turn back OFF (don't heat) after an individual max heating delay
#     => Max heating delay restart everytime a switch command ON is received (through API or binary sensor)
#     => Max heating delay turn OFF the linked switch
#   - 
# 
# Features:
#   1- 4 switches 'heater_<n>' and their respective binary sensors 'toggle_<n>' are exposed
#     => Switches state is a 'Should be'
#   2- 4 relays 'relay_<n> are exposed for diagnostic purpose ONLY
#     => They are the real state of the heaters
#     /!\ Avoid direct modification of their state, it could damage your device and will disturb the timers
#   2- 'Apply delay' and 'Max heating delay' can be configured globaly (not individualy)
#   3- 'Apply delay' and 'Max heating delay' are saved/restored from flash
# 
# Usage:
#   - secrets.yaml file must include:
#       wifi_ssid: to_be_complated
#       wifi_password: to_be_complated
#   - Compile and upload
# ---------------------------------------------

# Pin definition
# GPIO0 Push Button 1 (HIGH = off, LOW = on)
# GPIO9 Push Button 2 (HIGH = off, LOW = on)
# GPIO10 Push Button 3 (HIGH = off, LOW = on)
# GPIO14 Push Button 4 (HIGH = off, LOW = on)
# GPIO12 Relay 1 and its status LED
# GPIO5 Relay 2 and its status LED
# GPIO4 Relay 3 and its status LED
# GPIO15 Relay 4 and its status LED
# GPIO13 Blue LED (HIGH = off, LOW = on)
#
# /!\ Using the Status LED on the 4CH Pro may cause relay 4 to activate on power up!
#     => Which is perfectly ok with our usage of the relays!

esphome:
  name: sonoff_4chpror2_heaters
  name_add_mac_suffix: true
  friendly_name: Sonoff 4CH PRO r2 Heaters
  project:
    name: "baldhor.sonoff_4chpror2_heaters"
    version: "1.0.0"

esp8266:
  board: esp01_1m
  restore_from_flash: true

preferences:
  flash_write_interval: 1min

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap: {} # This spawns an AP with the device name and mac address with no password.

api:
  encryption:
    key: !secret api_encryption_key
  #password: !secret api_password

#mqtt:
#  broker: !secret mqtt_broker
#  port: !secret mqtt_port
#  username: !secret mqtt_login
#  password: !secret mqtt_password

ota:
  password: !secret ota_password

# Enable logging
logger:
  baud_rate: 0
  level: DEBUG #(by default)
#  level: VERBOSE
#  level: VERY_VERBOSE

# The mdns component makes the node announce itself on the local network using the multicast DNS (mDNS) protocol.
# If mDNS is disabled, it will be impossible to automatically find your devices.
mdns:
  disabled: true

web_server:
  port: 80

captive_portal:

# Maintain date/time up to date
#time:
#  - platform: sntp
#    id: my_time

# Announce wifi connexion
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      disabled_by_default: true

# Announce uptime every minute
sensor:
  - platform: uptime
    name: "Uptime"
    disabled_by_default: true

number:
  - id: apply_delay
    platform: template
    name: "Apply delay (in seconds)"
    disabled_by_default: true
    optimistic: true
    min_value: 1
    max_value: 10
    step: 1
    restore_value: true
    initial_value: 3
    mode: box
    entity_category: config

  - id: max_heating_delay
    platform: template
    name: "Max heating delay (in minutes)"
    disabled_by_default: true
    optimistic: true
    min_value: 1
    max_value: 10
    step: 1
    restore_value: true
    initial_value: 5
    mode: box
    entity_category: config

binary_sensor:
  - id: Status
    platform: status
    name: "Status"
    disabled_by_default: true

  - id: toggle_1
    platform: gpio
    name: "Toggle heater 1"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: heater_1

  - id: toggle_2
    platform: gpio
    name: "Toggle heater 2"
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: heater_2

  - id: toggle_3
    platform: gpio
    name: "Toggle heater 3"
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: heater_3

  - id: toggle_4
    platform: gpio
    name: "Toggle heater 4"
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: heater_4

script:
  - id: apply_delay_1
    mode: single
    then:
      - delay: !lambda return id(apply_delay).state * 1000;
      - lambda: !lambda |-
          id(relay_1).publish_state(id(heater_1).state);
      
  - id: apply_delay_2
    mode: single
    then:
      - delay: !lambda return id(apply_delay).state * 1000;
      - lambda: !lambda |-
          id(relay_2).publish_state(!id(heater_2).state);
      
  - id: apply_delay_3
    mode: single
    then:
      - delay: !lambda return id(apply_delay).state * 1000;
      - lambda: !lambda |-
          id(relay_3).publish_state(!id(heater_3).state);
      
  - id: apply_delay_4
    mode: single
    then:
      - delay: !lambda return id(apply_delay).state * 1000;
      - lambda: !lambda |-
          id(relay_4).publish_state(!id(heater_4).state);
      
  - id: max_heating_delay_1
    mode: single
    then:
      - delay: !lambda return id(max_heating_delay).state * 60000;
      - switch.turn_on: relay_4

  - id: max_heating_delay_2
    mode: single
    then:
      - delay: !lambda return id(max_heating_delay).state * 60000;
      - switch.turn_on: relay_4

  - id: max_heating_delay_3
    mode: single
    then:
      - delay: !lambda return id(max_heating_delay).state * 60000;
      - switch.turn_on: relay_4

  - id: max_heating_delay_4
    mode: single
    then:
      - delay: !lambda return id(max_heating_delay).state * 60000;
      - switch.turn_on: relay_4

switch:
  - id: heater_1
    platform: template
    name: "Template Switch"
    optimistic: true
    restore_mode: ALWAYS_OFF
    turn_on_action:
      then:
        lambda: !lambda |-
          if (!id(apply_delay_1).is_running()) {
            id(apply_delay_1).execute();
          }
    turn_off_action:
      then:
        lambda: !lambda |-
          if (!id(apply_delay_1).is_running()) {
            id(apply_delay_1).execute();
          }

  - id: heater_2
    platform: template
    name: "Template Switch"
    optimistic: true
    restore_mode: ALWAYS_OFF
    turn_on_action:
      then:
        lambda: !lambda |-
          if (!id(apply_delay_2).is_running()) {
            id(apply_delay_2).execute();
          }
    turn_off_action:
      then:
        lambda: !lambda |-
          if (!id(apply_delay_2).is_running()) {
            id(apply_delay_2).execute();
          }

  - id: heater_3
    platform: template
    name: "Template Switch"
    optimistic: true
    restore_mode: ALWAYS_OFF
    turn_on_action:
      then:
        lambda: !lambda |-
          if (!id(apply_delay_3).is_running()) {
            id(apply_delay_3).execute();
          }
    turn_off_action:
      then:
        lambda: !lambda |-
          if (!id(apply_delay_3).is_running()) {
            id(apply_delay_3).execute();
          }

  - id: heater_4
    platform: template
    name: "Template Switch"
    optimistic: true
    restore_mode: ALWAYS_OFF
    turn_on_action:
      then:
        lambda: !lambda |-
          if (!id(apply_delay_4).is_running()) {
            id(apply_delay_4).execute();
          }
    turn_off_action:
      then:
        lambda: !lambda |-
          if (!id(apply_delay_4).is_running()) {
            id(apply_delay_4).execute();
          }

  - id: relay_1
    platform: gpio
    name: "Relay 1"
    pin: GPIO12
    disabled_by_default: true
    restore_mode: ALWAYS_ON
    turn_on_action:
      then:
        - script.stop: max_heating_delay_1
    turn_off_action:
      then:
        - script.execute: max_heating_delay_1

  - id: relay_2
    platform: gpio
    name: "Relay 2"
    pin: GPIO5
    disabled_by_default: true
    restore_mode: ALWAYS_ON
    turn_on_action:
      then:
        - script.stop: max_heating_delay_2
    turn_off_action:
      then:
        - script.execute: max_heating_delay_2

  - id: relay_3
    platform: gpio
    name: "Relay 3"
    pin: GPIO4
    disabled_by_default: true
    restore_mode: ALWAYS_ON
    turn_on_action:
      then:
        - script.stop: max_heating_delay_3
    turn_off_action:
      then:
        - script.execute: max_heating_delay_3

  - id: relay_4
    platform: gpio
    name: "Relay 4"
    pin: GPIO15
    disabled_by_default: true
    restore_mode: ALWAYS_ON
    turn_on_action:
      then:
        - script.stop: max_heating_delay_3
    turn_off_action:
      then:
        - script.execute: max_heating_delay_3

light:
  - id: status_led1
    platform: status_led
    disabled_by_default: true
    pin:
      number: GPIO13
      inverted: true
